# Generated by Django 5.1.2 on 2024-10-18 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adoption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email_id', models.EmailField(max_length=254)),
                ('contact', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('occupation', models.CharField(max_length=100)),
                ('adults', models.IntegerField()),
                ('children', models.IntegerField()),
                ('allergy', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('Maybe', 'Maybe')], max_length=10)),
                ('agreement', models.BooleanField()),
                ('time_for_pet', models.BooleanField()),
                ('experience', models.BooleanField()),
                ('pet_name', models.CharField(max_length=100)),
                ('pet_gender', models.CharField(max_length=10)),
                ('aadhar_number', models.CharField(max_length=12)),
                ('consent_form', models.FileField(upload_to='consents/')),
                ('regular_updates', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('Maybe', 'Maybe')], max_length=10)),
                ('pet_photo', models.ImageField(upload_to='pets/')),
            ],
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_id', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=15)),
                ('payment_screenshot', models.ImageField(upload_to='payments/')),
            ],
        ),
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('member_type', models.CharField(max_length=50)),
                ('affiliation', models.CharField(max_length=100)),
                ('residence', models.CharField(max_length=20)),
                ('experience_with_animals', models.BooleanField()),
                ('volunteer_areas', models.TextField()),
                ('reason_for_volunteering', models.TextField()),
            ],
        ),
    ]
