# Generated by Django 5.1.2 on 2024-11-04 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adoptions', '0002_alter_adoption_agreement_alter_adoption_experience_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreAdoption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
                ('phone', models.CharField(max_length=15)),
                ('dog_name', models.CharField(blank=True, max_length=100, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='uploads/pet_photos/')),
                ('owned_pets', models.BooleanField()),
                ('other_pets', models.BooleanField()),
                ('schedule', models.TextField()),
                ('financially_prepared', models.BooleanField()),
            ],
        ),
    ]
